Barbapapazes/slidev-theme-aneo

.github/workflows/publish.yml, package-lock.json, package.json, scripts/publish.mjs
=> feat: add ci to auto publish

package.json, scripts/publish.mjs
=> release: 0.0.1

example.md, package.json, styles/layout.css
=> fix: update sans serif font to poppins

example.md, layoutHelper.ts, layouts/cover.vue, styles/layout.css
=> refactor: cover props

package.json
=> release: 0.0.3

example.md, layouts/summary.vue, styles/layout.css
=> feat: create layout summary

example.md, layouts/section.vue
=> fix: section background

package.json
=> release: 0.0.4

styles/layout.css
=> fix: text size in summary layout

example.md, layouts/two-cols.vue
=> feat: add two-cols layout

package.json
=> release: 0.0.5

example.md, styles/layout.css
=> fix(cover): title color in white theme

components/SlideNumber.vue, layouts/default.vue, layouts/two-cols.vue, styles/layout.css
=> feat(components): create slide number

example.md, package.json, setup/shiki.ts
=> fix(code): change highliter

package.json
=> release: 0.0.6

components/SlidesTitle.vue, layouts/default.vue, styles/layout.css
=> feat(components): add title to the bottom

components/Author.vue, example.md, layouts/default.vue, styles/layout.css
=> feat(components): add author

components/SlideNumber.vue, styles/layout.css
=> fix(components): slide number

layouts/section.vue
=> fix(layout): section icon

components/SlidesStatus/SlidesStatus.vue, components/SlidesStatus/SlidesStatusAuthor.vue, components/SlidesStatus/SlidesStatusNumber.vue, components/SlidesStatus/SlidesStatusTitle.vue, layouts/default.vue, layouts/two-cols.vue, styles/layout.css
=> feat(components): add slides status

LICENSE, package.json
=> chore: add mit license

.docs/content/1.guide/0.index.md, .docs/content/1.guide/1.customize.md, .docs/nuxt.config.ts, README.md
=> docs: improve

.github/workflows/deply-docs.yml
=> ci: fix env

example.md, styles/layout.css
=> fix: `code` style

components/Alert.vue, example.md, styles/layout.css, types/color.ts
=> feat: create alert

components/SlidesStatus/SlidesStatusAuthor.vue, components/SlidesStatus/SlidesStatusNumber.vue, components/SlidesStatus/SlidesStatusTitle.vue
=> feat: can disable part of slides status

example.md, layouts/cover.vue
=> fix(layouts): add default to cover

.github/workflows/deply-docs.yml
=> ci: fix deployment path

.docs/content/2.API/components.md
=> docs: add alert section

components/SlidesStatus/SlidesStatus.vue, components/SlidesStatus/SlidesStatusNumber.vue, example.md
=> fix: position when some parts of status are disabled

example.md, styles/layout.css
=> fix: alert margin

components/Alert.vue
=> fix: alert text color

.docs/app.config.ts, .docs/content/1.guide/0.index.md, .docs/content/1.guide/1.customize.md, .docs/content/1.guide/1.writing.md, .docs/content/1.guide/2.customizing.md, .docs/content/1.guide/3.exporting.md, .docs/content/1.guide/_dir.yml, .docs/content/2.API/_dir.yml, .docs/content/2.API/layouts.md
fix #101
fix #109 
fix #85
fix #98 
fix #96
fix #111
=> docs: update

README.md
=> docs: update contributing

styles/layout.css
=> fix: pre code padding

components/Logo.vue, components/SeeMore.vue, example.md, layouts/cover.vue, layouts/default.vue, layouts/toc.vue, layouts/two-cols.vue
=> fix: icon aneo

example.md, layouts/cover.vue, styles/layout.css
=> fix(layouts): center cover title and logo

components/Logo.vue, components/SlidesStatus/SlidesStatus.vue, components/SlidesStatus/SlidesStatusAuthor.vue, components/SlidesStatus/SlidesStatusNumber.vue, components/SlidesStatus/SlidesStatusTitle.vue, layouts/default.vue, layouts/section.vue, layouts/two-cols.vue
=> fix: logo position

.docs/content/2.API/components.md, .vscode/settings.json, components/Alert.vue, example.md, setup/windicss.ts, styles/components.css, styles/index.ts
=> fix: alert padding and colors

example.md, layouts/content-center.vue
=> feat: create a content center layout

.docs/content/2.API/components.md, .vscode/settings.json
=> docs: add how to use components

.docs/content/2.API/layouts.md, example.md, layouts/two-cols.vue
=> fix: two cols layouts

example.md
=> docs: add more toc in example.md

.docs/content/1.guide/1.writing.md, example.md, styles/layout.css
=> fix: heading usage

.docs/content/2.API/components.md, .docs/content/2.API/layouts.md
=> docs: add icons to api pages

.docs/content/2.API/layouts.md
=> docs: add center layout

styles/layout.css
=> fix: subtitle color

.docs/app.config.ts
=> docs: add footer text link

.docs/content/2.API/layouts.md
=> docs: add see more

.docs/content/2.API/layouts.md
=> docs: add see more in other layouts

.docs/content/2.API/components.md, example.md
fix #187 
@aneojgurhem tout est là !
=> docs: add transform components

example.md, example_2.md
=> docs: add src example

.github/workflows/publish.yml
=> ci: add changelogithub

.docs/content/2.API/components.md, components/SectionContent.vue, example.md, styles/components.css
=> feat: create section-content component

.docs/content/2.API/components.md, components/Separator.vue, example.md
=> feat: create separator component
